query AllCarpools($search: SearchArgs!, $sort: SortArgs) {
  getAllCarpools(search: $search, sort: $sort) {
    id
    departure_time
    arrival_time
    departure {
      address
      city
      country
      postal_code
    }
    arrival {
      address
      city
      country
      postal_code
    }
    participants {
      participant_type
      user {
        username
      }
    }
    price
    max_passengers
    carpool_type
  }
}
